# $HOME/.config/alacritty/alacritty.toml

[window]
opacity = 0.9
title = "Term-Alacritty"

[font]
normal.family = "JetBrainsMono NF Light"
bold.family = "JetBrainsMono NF Medium"
italic.family = "JetBrainsMono NF Light Italic"
bold_italic.family = "JetBrainsMono NF Medium Italic"
size = 15.0

