#################
### AUTOSTART ###
#################

exec-once = waybar & hyprpaper & hypridle # & swaync
exec-once = systemctl --user start hyprpolkitagent

exec-once = [workspace 1 silent] $terminal
exec-once = [workspace e silent] $browser
# exec-once = nm-applet &

# exec = gsettings set org.gnome.desktop.interface gtk-theme "YOUR_THEME_NAME" # For GTK3 apps
# exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"  # For GTK4 apps
