#################
### AUTOSTART ###
#################

exec-once = waybar & hyprpaper & hypridle # & swaync
exec-once = $terminal
# exec-once = nm-applet &

# exec = gsettings set org.gnome.desktop.interface gtk-theme "YOUR_THEME_NAME" # For GTK3 apps
# exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"  # For GTK4 apps
