theme = "catppuccin_frappe"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"
true-color = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
"'" = "'"
'"' = '"'

[editor.file-picker]
hidden = false

[editor.terminal]
command = "kitty"
args = ["-e"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.insert]
"C-ret" = "completion"
"C-backspace" = "delete_word_backward"# At most one section each of 'keys.normal', 'keys.' and 'keys.select'

[keys.normal]
"tab" = "completion"
"C-/" = "toggle_comments"
"C-." = ":open ~/.config/helix/config.toml"
"C-," = ":config-reload"

[keys.normal.space.r]
a = ":sh alr run"                 # Ada / Alire
r = ":sh cargo run"               # Rust
g = ":sh go run ."                # Go
j = ":sh node \"%{buffer_name}\"" # JavaScript
m = ":sh make run"                # Make

[keys.select]
C-z = "undo"
C-r = "redo"
