theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.insert]
"C-ret" = "completion"

# At most one section each of 'keys.normal', 'keys.' and 'keys.select'
[keys.normal]
"tab" = "completion"
"ret" = "insert_mode"
"C-/" = "toggle_comments"
"C-." = ":open ~/.config/helix/config.toml"
"C->" = ":config-reload"
C-z = "undo"
C-r = "redo"
C-s = "save_selection"
C-i = "jump_forward"
C-n = "jump_backward"
# C-s = ":w"
C-X = "increment"
c = "yank"
j = "change_selection"
b = "search_next"
B = "search_prev"
n = "move_char_left" # Maps the 'n' key to the move_char_left command
u = "move_line_up" # Maps the 'u' key move_line_up
i = "move_char_right" # Maps the 'n' key to the move_char_left command
e = "move_line_down" # Maps the 'u' key move_line_up
l = "move_prev_word_start"
L = "move_prev_long_word_start"
y = "move_next_word_start"
Y = "move_next_long_word_start"
w = "move_next_word_end"
W = "move_next_long_word_end"
h = "goto_line_start"
o = "goto_line_end"
g = { h = "goto_file_start", n = "goto_line_start",  i = "goto_line_end", u = "move_line_up", e = "move_line_down", o = "goto_last_line" }
A-u = "expand_selection"
A-e = "shrink_selection"
A-n = "select_prev_sibling"
A-i = "select_next_sibling"
A-a = "select_all_siblings"	
A-E = "select_all_children"
A-l = "move_parent_node_start"
A-y = "move_parent_node_end"

[keys.select]
C-z = "undo"
C-r = "redo"
C-i = "insert_mode"
c = "yank"
j = "change_selection"
b = "extend_search_next"
B = "extend_search_prev"
n = "extend_char_left" # Maps the 'n' key to the extend_char_left command
u = "extend_line_up" # Maps the 'u' key extend_line_up
i = "extend_char_right" # Maps the 'n' key to the extend_char_left command
e = "extend_line_down" # Maps the 'u' key extend_line_up
l = "extend_prev_word_start"
L = "extend_prev_long_word_start"
y = "extend_next_word_start"
Y = "extend_next_long_word_start"
w = "extend_next_word_end"
W = "extend_next_long_word_end"
g = { n = "goto_line_start",  i = "goto_line_end", u = "extend_line_up", e = "extend_line_down", o = "goto_last_line" }
